#!/usr/bin/env bash
# Concatenates every migration, in filename order, into one file you can paste
# into the Supabase SQL editor in a single go.
#
#   npm run db:bundle    ->  supabase/schema.bundle.sql
#
# The bundle is generated and gitignored: the migrations remain the source of
# truth, so this can never drift from them. Use it for the first setup of a
# hosted project; after that, `npm run db:push` applies new migrations
# incrementally.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/supabase/schema.bundle.sql"

{
  echo "-- Offer Desk schema bundle - generated by scripts/bundle-schema.sh"
  echo "-- Do not edit. Edit the files in supabase/migrations/ and regenerate."
  echo "-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "begin;"
  echo
  for file in "$ROOT"/supabase/migrations/*.sql; do
    echo "-- ============================================================"
    echo "-- $(basename "$file")"
    echo "-- ============================================================"
    cat "$file"
    echo
  done
  echo "commit;"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT") lines)"
